language: node_js
node_js:
  - "0.12.7"
  - "4"
  - "5"
  - "6"
matrix:
  fast_finish: true
  allow_failures:
    - node_js: "6" 
script: "npm run-script test"
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
after_script: "cp ./coverage/Fire*/lcov.info ./coverage && ls -cal ./coverage && npm install coveralls@2.11.9 && cat ./coverage/lcov.info | coveralls"
